### ISSUE TITLE
Execution order

### ISSUE THREAD

**Issue by JaimeCalzadaNOAA** [noaa-ocs-modeling/nemspy#7]
https://github.com/noaa-ocs-modeling/NEMSpy/blob/33323ae4135ca0b9cd3679bd7e53f6919afc0ad2/examples/example_1.py#L15-L20
How is the execution order defined?

**Comment by zacharyburnettNOAA** [comment]
https://github.com/noaa-ocs-modeling/NEMSpy/blob/33323ae4135ca0b9cd3679bd7e53f6919afc0ad2/examples/example_1.py#L11-L20

the order is currently defined by the `.__init__()` order, but I'm trying to think of a better way to define that more explicitly

**Comment by zacharyburnettNOAA** [comment]
https://github.com/noaa-ocs-modeling/NEMSpy/commit/36bcb8e400d7b902d6f882885a9de1ecb0a8b8e4

**Comment by zacharyburnettNOAA** [comment]
made a pull request (#8 ) for mutable sequence

**Comment by jreniel** [comment]
> https://github.com/noaa-ocs-modeling/NEMSpy/blob/33323ae4135ca0b9cd3679bd7e53f6919afc0ad2/examples/example_1.py#L11-L20
> 
> the order is currently defined by the `.__init__()` order, but I'm trying to think of a better way to define that more explicitly

I think we might need more than that, since the execution is not just about ordering, it can also call specific functions from the CAP. In this case, I think we need to make it so that the user builds the whole sequence (connectors, executors and subsequences) from the API methods.

**Comment by zacharyburnettNOAA** [comment]
alright, I will keep working on that

**Comment by zacharyburnettNOAA** [comment]
sequence API implemented in #8; second half of this issue is moved to #13
